import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';

const nunito = Nunito({
  variable: '--font-nunito',
  subsets: ['cyrillic'],
  weight: ['400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Next Pizza | Dashboard',
  description: 'Dashboard Generated by create next app',
};

export default function DashboardLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={nunito.variable}>
        <main className='min-h-screen'>{children}</main>
      </body>
    </html>
  );
}
